13/FS Codegen Config & 7/FE Set up field to display queried data
Los-Terremotos/GreenPets pull request #37
Opened 2023-12-16 03:36 UTC by KP824

## Overview

**13/FS Codegen & GraphQL Config & 7/FE Set up field to display queried data**

- [ ] Bug
- [x] Feature
- [ ] Tech Debt

**Description**
- Implemented and configured GraphQL Codegen (typescript generator) for both client & server folders
- Running script `npm run codegen` in either client/server folder, will generate "types.ts" file that will contain all proper Typescript typing for everything declared within the GraphQL Schema.ts file
- Back end routes for GraphQL have been successfully set up
- Running queries from the Apollo Server GUI, will now successfully return live data from the Perenual API
- Created Test Field tab on the Home Page that will successfully show live data that is fetched from the Perenual API

**Ticket Item**
#13 
#7 

**Steps to Reproduce Bug / Validate Feature / Confirm Tech Debt Fix**
1. Go to server folder with `cd server`
2. Then install new dependencies, `npm install`
3. Run codegen to validate types for Typescript are generated, with `npm run codegen`
4. Start the dev server, `npm run dev`
5. Open up a new terminal and navigate to the client folder, `cd client`
6. Install new dependencies, `npm install`
7. Run codegen within the client folder with `npm run codegen`. Should see `__generated__` folder generate within the `src` folder
8. Run the front end server with `npm run start`
9. Open the browser at [http://localhost:5173/](url), and navigate to the Test Field tab
10. Verify that a single plant data and image is being displayed on the front end
11. Be sure to inspect the page and check the console tab. Should be able to see a console log of the entire list of plants that have been returned from the API fetch request

   
**Previous behavior**
- Codegen was not fully configured and the GraphQL schema did not have proper typing
- No implementation of GraphQL within the client folder

**Expected behavior**
- Have successfully connected the front end with the back end GraphQL endpoints
- Front end test fields able to fetch plant information and change inputs to fetch dynamic information

**Screenshots & Videos**
*This is after running step 3*
![This is after running step 3](https://github.com/Los-Terremotos/GreenPets/assets/112226540/f720d444-15ff-4184-83bf-46481cead604)

*This is after running step 7*
![This is after running step 7](https://github.com/Los-Terremotos/GreenPets/assets/112226540/f94a7ce4-a172-4fe1-b25c-66d5afa9bf14)

*This is after running step 11*
![This is validation at step 11](https://github.com/Los-Terremotos/GreenPets/assets/112226540/c08ed8f2-d757-416e-8a3c-1cc90a51c21c)

**Additional context**
- To validate these features, both server and client server need to be running at the same time
- You can change the inputs for the fetch request within the `client/src/pages/TestDisplay.tsx` page on lines 112 & 113.
- Please note **inputNumber = 1** will return an **empty** response!
- There are two `useEffect` functions commented out that will render both Perenual API's with live data within the same page, if uncommented 
- Please refer to the `group_logs` for detailed description of implementation of these features.

2023-12-16 17:07 UTC, jennyschmalz approved these changes

2023-12-16 17:11 UTC, jennyschmalz requested changes
Resolve merge conflicts with daily logs

2023-12-18 15:01 UTC, stephanie-115 approved these changes
Great work, KP!

2023-12-18 15:46 UTC, crisdevs approved these changes
Looking good to me!

2023-12-18 17:37 UTC, merged